services:
  prod:
    container_name: svelte_documentation_tutorial_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: always
